import type { AdminIntegration, Client } from "@/types/client";

export const CLIENTS: Client[] = [
  { id: 0, name: "Northwind Labs", email: "ops@northwindlabs.com", website: "northwindlabs.com", initials: "NL", industry: "B2B SaaS", updated: "2 days ago" },
  { id: 1, name: "Brightwave Media", email: "hello@brightwave.co", website: "brightwave.co", initials: "BM", industry: "Media", updated: "5 hours ago" },
  { id: 2, name: "Halcyon Health", email: "team@halcyonhealth.com", website: "halcyonhealth.com", initials: "HH", industry: "Healthcare", updated: "1 day ago" },
  { id: 3, name: "Vertex Logistics", email: "ops@vertexlogistics.io", website: "vertexlogistics.io", initials: "VL", industry: "Logistics", updated: "3 days ago" },
  { id: 4, name: "Lumen Retail", email: "growth@lumenretail.com", website: "lumenretail.com", initials: "LR", industry: "E-commerce", updated: "6 days ago" },
  { id: 5, name: "Cedar & Co.", email: "hello@cedarandco.com", website: "cedarandco.com", initials: "CC", industry: "B2B SaaS", updated: "1 week ago" },
];

export const INDUSTRIES = ["B2B SaaS", "E-commerce", "Healthcare", "Logistics", "Media"];

/** Admin Integrations tab — HubSpot & Salesforce use a CSV upload flow. */
export const ADMIN_INTEGRATIONS: AdminIntegration[] = [
  {
    id: "google",
    name: "Google Suite",
    categories: ["Analytics", "Ads", "Search Console"],
    logo: "/logos/google.svg",
    brandColor: "#4285f4",
    headerText: "light",
    isUpload: false,
    status: "connected",
    connectedDate: "7/15/2026",
    lastSync: "Pending",
    lastSynced: false,
  },
  {
    id: "hubspot",
    name: "HubSpot",
    categories: ["Contacts", "Deals", "Pipeline"],
    logo: "/logos/hubspot.svg",
    brandColor: "#f1f2ef",
    headerText: "dark",
    isUpload: true,
    status: "no_data",
    connectedDate: null,
    lastSync: "Pending",
    lastSynced: false,
    uploadHint:
      "Upload a HubSpot MQL attribution report (CSV) to ingest interactions for this client. The file must match the template.",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    categories: ["CSV upload", "Opportunities", "Pipeline"],
    logo: "/logos/salesforce.svg",
    brandColor: "#f1f2ef",
    headerText: "dark",
    isUpload: true,
    status: "no_data",
    connectedDate: null,
    lastSync: "Pending",
    lastSynced: false,
    uploadHint:
      "Upload a Salesforce report (CSV) to ingest opportunities for this client. The file must match the template.",
  },
  {
    id: "asana",
    name: "Asana",
    categories: ["Tasks", "Projects", "Workspaces"],
    logo: "/logos/asana.svg",
    brandColor: "#f06a6a",
    headerText: "light",
    isUpload: false,
    status: "connected",
    connectedDate: "7/8/2026",
    lastSync: "7/15/2026",
    lastSynced: true,
    syncedChips: ["208 tasks_synced", "1 projects_synced"],
  },
  {
    id: "semrush",
    name: "SEMrush",
    categories: ["Keywords", "Rankings", "Competitors"],
    logo: "/logos/semrush.svg",
    brandColor: "#ff642f",
    headerText: "light",
    isUpload: false,
    status: "connected",
    connectedDate: "7/2/2026",
    lastSync: "Pending",
    lastSynced: false,
  },
  {
    id: "fathom",
    name: "Fathom",
    categories: ["Meeting recordings", "Transcripts"],
    logo: "/logos/fathom.svg",
    brandColor: "#1b2733",
    headerText: "light",
    isUpload: false,
    status: "connected",
    connectedDate: "7/2/2026",
    lastSync: "7/15/2026",
    lastSynced: true,
  },
  {
    id: "reddit",
    name: "Reddit Ads",
    categories: ["Ad campaigns", "Reports", "Audiences"],
    logo: "/logos/reddit.svg",
    brandColor: "#ff4500",
    headerText: "light",
    isUpload: false,
    status: "connected",
    connectedDate: "7/2/2026",
    lastSync: "Pending",
    lastSynced: false,
  },
  {
    id: "slack",
    name: "Slack",
    categories: ["Channels", "Messages", "Digest delivery"],
    logo: "/logos/slack.svg",
    brandColor: "#3f0e40",
    headerText: "light",
    isUpload: false,
    status: "connected",
    connectedDate: "7/2/2026",
    lastSync: "Pending",
    lastSynced: false,
  },
  {
    id: "linkedin",
    name: "LinkedIn",
    categories: ["Ads", "Campaign analytics", "Pages"],
    logo: "/logos/linkedin.svg",
    brandColor: "#0a66c2",
    headerText: "light",
    isUpload: false,
    status: "connected",
    connectedDate: "7/8/2026",
    lastSync: "Pending",
    lastSynced: false,
  },
];
