import { ProfileFieldType, type ProfileStep } from "@/types/profile";

const { Text, Url, Number: Num, Select, MultiSelect, Area, BigArea, Chips, MinMax, Toggle } = ProfileFieldType;

export const PROFILE_STEPS: ProfileStep[] = [
  { id: "basic", title: "Basic Profile", subtitle: "Start with the core information required to create the client profile.", completion: 80, caption: "Client profile summary · Business overview", sections: [
    { title: "Client profile summary", count: "6 fields", fields: [
      { label: "Website", type: Url, placeholder: "Enter website", required: true },
      { label: "Business type", type: Select, placeholder: "Select business type", controlsBiz: true, options: ["B2B", "D2C", "B2B2C", "Hybrid"] },
      { label: "Category", type: Select, placeholder: "Select category", full: true, options: ["B2B SaaS", "B2C SaaS", "E-commerce", "Marketplace", "Agency / Services", "Fintech", "Healthcare", "Hardware", "Other"] },
      { label: "Primary growth motion", type: Area, placeholder: "Describe primary growth motion" },
      { label: "Primary AI digest goal", type: Text, placeholder: "Enter primary AI digest goal", full: true, required: true },
      { label: "Main reporting risk", type: Area, placeholder: "Describe main reporting risk" },
    ] },
    { title: "Business overview", count: "7 fields", fields: [
      { label: "Business overview", type: BigArea, placeholder: "Describe business overview", required: true },
      { label: "Industry", type: Select, placeholder: "Select industry", required: true, full: true, allowAddOption: true, options: ["Healthcare", "Medical Devices", "SaaS", "Fintech", "E-commerce / Retail", "Manufacturing", "Education", "Professional Services"] },
      { label: "Demand quality requirement", type: Area, placeholder: "Describe the demand quality requirement" },
      { label: "Bad-fit lead risk", type: Area, placeholder: "Describe the bad-fit lead risk" },
      { label: "Regulated industry?", type: Toggle },
      { label: "Regulatory environment", type: Chips, placeholder: "Add regulatory environment", chips: [], showWhenToggle: "Regulated industry?" },
      { label: "Buying motions", type: Chips, placeholder: "Add buying motions", chips: [] },
    ] },
  ] },
  { id: "kpis", title: "KPIs & Objectives", subtitle: "Define the metrics that measure growth and the objectives behind them.", completion: 40, caption: "Primary & secondary KPIs · Goals & objectives", sections: [
    { title: "Primary and secondary KPIs", count: "3 fields", fields: [
      { label: "North star metric", type: Text, placeholder: "Enter north star metric", required: true, full: true },
      { label: "Primary KPIs", type: MultiSelect, placeholder: "Add primary KPIs", required: true, full: true, allowAddOption: true, options: ["Qualified demos booked", "MQLs", "SQLs", "Pipeline created", "Conversion rate", "Cost per acquisition", "Cost per lead"], chips: ["MQLs", "Pipeline created", "SQLs", "Cost per acquisition"] },
      { label: "Secondary KPIs", type: Chips, placeholder: "Add secondary KPIs", chips: [] },
    ] },
    { title: "Goals and objectives", count: "1 field", fields: [
      { label: "Confirmed objectives", type: Area, placeholder: "Add confirmed objectives" },
    ] },
  ] },
  { id: "audience", title: "Audience & ICP", subtitle: "Describe who you sell to and how the audience is segmented.", completion: 20, caption: "Target audience / ICP · Audience & segmentation", sections: [
    { title: "Target audience / ICP", count: "6 fields", fields: [
      { label: "Company type", type: Chips, placeholder: "Add company types", required: true, chips: [] },
      { label: "Company stage / maturity", type: Chips, placeholder: "Add company stages", chips: [] },
      { label: "Geography", type: Chips, placeholder: "Add geography", chips: [] },
      { label: "Functional buyers", type: Chips, placeholder: "Add functional buyers", chips: [] },
      { label: "Target titles", type: Chips, placeholder: "Add target titles", chips: [] },
      { label: "Bad-fit / low-fit audiences", type: Chips, placeholder: "Add bad-fit / low-fit audiences", chips: [] },
    ] },
    { title: "Audience & segmentation", count: "20 fields", fields: [
      { label: "Target industries", type: MultiSelect, placeholder: "Select options", requiresBiz: true, options: ["Technology", "Healthcare", "Financial Services", "Manufacturing", "Retail", "Education", "Media", "Other"] },
      { label: "Company size", type: Select, placeholder: "Select option", requiresBiz: true, options: ["1–50", "51–200", "201–1,000", "1,000+"] },
      { label: "Revenue range", type: Select, placeholder: "Select option", requiresBiz: true, options: ["< $1M", "$1M–$10M", "$10M–$50M", "$50M–$250M", "$250M+"] },
      { label: "Geography served", type: MultiSelect, placeholder: "Select options", requiresBiz: true, options: ["North America", "EMEA", "APAC", "LATAM", "Global"] },
      { label: "Target departments", type: MultiSelect, placeholder: "Select options", requiresBiz: true, options: ["Marketing", "Sales", "Engineering", "Operations", "Finance", "HR", "IT", "Product"] },
      { label: "Buyer titles", type: MultiSelect, placeholder: "Select options", requiresBiz: true, options: ["C-level", "VP", "Director", "Manager", "Individual contributor"] },
      { label: "Pain points by role", type: Text, requiresBiz: true },
      { label: "Compliance requirements", type: Text, requiresBiz: true },
      { label: "Existing competitors", type: Text, placeholder: "Competitors the buyer already uses or evaluates", requiresBiz: true },
      { label: "Procurement objections", type: Text, requiresBiz: true },
      { label: "Target demographics", type: Text, requiresBiz: true },
      { label: "Psychographics", type: Text, requiresBiz: true },
      { label: "Lifestyle triggers", type: Text, requiresBiz: true },
      { label: "Purchase occasions", type: Text, requiresBiz: true },
      { label: "Gift vs self-purchase", type: Select, placeholder: "Select option", requiresBiz: true, options: ["Gift", "Self", "Both"] },
      { label: "Price sensitivity", type: Select, placeholder: "Select option", requiresBiz: true, options: ["Low", "Medium", "High"] },
      { label: "Product preference drivers", type: MultiSelect, placeholder: "Select options", requiresBiz: true, options: ["Price", "Quality", "Brand", "Features", "Support", "Convenience"] },
      { label: "Pre-purchase objections", type: Text, requiresBiz: true },
      { label: "Reviews / testimonials", type: Text, requiresBiz: true },
      { label: "UGC available?", type: Select, placeholder: "Select option", requiresBiz: true, options: ["Yes", "No"] },
    ] },
  ] },
  { id: "products", title: "Products & Offer", subtitle: "Detail what you sell and how complex the offer is to buy.", completion: 0, caption: "Products & services · Offer & product complexity", sections: [
    { title: "Products and services", count: "", variant: "products", fields: [] },
    { title: "Offer & product complexity", count: "8 fields", fields: [
      { label: "Product / service complexity", type: Select, placeholder: "Select option", options: ["Low", "Medium", "High"] },
      { label: "Customization required?", type: Select, placeholder: "Select option", options: ["Yes", "No"] },
      { label: "Implementation required?", type: Select, placeholder: "Select option", options: ["Yes", "No"] },
      { label: "Onboarding process", type: Text },
      { label: "Number of SKUs", type: Num },
      { label: "Product variants?", type: Select, placeholder: "Select option", options: ["Yes", "No"], requiresBiz: true },
      { label: "Shipping / fulfillment?", type: Select, placeholder: "Select option", options: ["Yes", "No"], requiresBiz: true },
      { label: "Returns / refunds policy URL", type: Url, placeholder: "https://...", requiresBiz: true },
    ] },
  ] },
  { id: "competitors", title: "Competitors & Campaigns", subtitle: "Capture the competitive landscape and current marketing activity.", completion: 0, caption: "Competitors · Active campaigns · Channel mix", sections: [
    { title: "Competitors", count: "", variant: "competitors", fields: [] },
    { title: "Active campaigns and projects", count: "5 fields", fields: [
      { label: "SEO and organic growth", type: Area, placeholder: "Describe SEO and organic growth work" },
      { label: "Paid search", type: Area, placeholder: "Describe paid search campaigns" },
      { label: "LinkedIn", type: Area, placeholder: "Describe LinkedIn campaigns" },
      { label: "Reddit", type: Area, placeholder: "Describe Reddit campaigns" },
      { label: "CRO projects", type: Area, placeholder: "Describe CRO projects" },
    ] },
    { title: "Marketing channel mix", count: "9 fields", fields: [
      { label: "Current acquisition channels", type: MultiSelect, placeholder: "Select options", options: ["SEO / Organic", "Paid search", "Paid social", "LinkedIn", "Reddit", "Email", "Referrals", "Events", "Content / PR", "Outbound"] },
      { label: "Primary paid channel", type: Select, placeholder: "Select option", options: ["Google Ads", "LinkedIn Ads", "Meta Ads", "Reddit Ads"] },
      { label: "Organic search focus", type: Select, placeholder: "Select option", options: ["Brand", "Non-brand", "Both", "Not a focus"] },
      { label: "Social proof assets", type: MultiSelect, placeholder: "Select options", options: ["Case studies", "Testimonials", "Reviews", "Logos", "Ratings / awards", "UGC"] },
      { label: "Influencer / creator strategy?", type: Select, placeholder: "Select option", options: ["Yes", "No"], requiresBiz: true },
      { label: "Sales outbound motion?", type: Select, placeholder: "Select option", options: ["Yes", "No"], requiresBiz: true },
      { label: "Affiliate program?", type: Select, placeholder: "Select option", options: ["Yes", "No"] },
      { label: "Partner / channel sales?", type: Select, placeholder: "Select option", options: ["Yes", "No"], requiresBiz: true },
      { label: "Highest-quality customer channel", type: Select, placeholder: "Select option", options: ["Referrals", "SEO / Organic", "Paid search", "Paid social", "Outbound", "Events", "Partnerships"] },
    ] },
  ] },
  { id: "buyer", title: "Buyer, Sales & Funnel", subtitle: "Map how customers buy, the sales motion, revenue model, and funnel.", completion: 0, caption: "Buyer structure · Sales · Revenue · Funnel · Signals", sections: [
    { title: "Customer / buyer structure", count: "7 fields", fields: [
      { label: "Primary buyer type", type: Select, placeholder: "Select option", options: ["Economic buyer", "Technical buyer", "User buyer", "Champion", "Decision maker"] },
      { label: "People involved in purchase", type: Text },
      { label: "Buyer role", type: MultiSelect, placeholder: "Select options", options: ["Executive sponsor", "Decision maker", "Influencer", "Evaluator", "End user", "Procurement", "Finance"], requiresBiz: true },
      { label: "End user differs from buyer?", type: Select, placeholder: "Select option", options: ["Yes", "No"] },
      { label: "Buyer vs user notes", type: Text, placeholder: "Optional: how the buyer and end user differ" },
      { label: "Account type (household vs company)", type: Select, placeholder: "Select option", options: ["Household", "Company"] },
      { label: "Customer examples", type: Area, placeholder: "Representative customers or accounts" },
    ] },
    { title: "Sales motion", count: "7 fields", fields: [
      { label: "Primary conversion goal", type: Select, placeholder: "Select option", options: ["Book a demo", "Start free trial", "Buy online", "Contact sales", "Sign up", "Add to cart"], requiresBiz: true },
      { label: "Sales cycle length", type: Select, placeholder: "Select option", options: ["< 1 week", "1–4 weeks", "1–3 months", "3–6 months", "6+ months"] },
      { label: "Human sales involvement", type: Select, placeholder: "Select option", options: ["None", "Light", "Heavy"] },
      { label: "Pricing visibility", type: Select, placeholder: "Select option", options: ["Public", "Gated"] },
      { label: "Contract required?", type: Select, placeholder: "Select option", options: ["Yes", "No"] },
      { label: "Purchase approval required?", type: Select, placeholder: "Select option", options: ["Yes", "No"] },
      { label: "Can a new customer buy online without talking to sales?", type: Select, placeholder: "Select option", options: ["Yes", "No"] },
    ] },
    { title: "Revenue model", count: "8 fields", fields: [
      { label: "Avg order / contract value ($)", type: MinMax },
      { label: "Revenue unit", type: Select, placeholder: "Select option", options: ["Per seat", "Per order", "Per user", "Per month", "Per year", "One-time"] },
      { label: "Repeat purchase frequency", type: Select, placeholder: "Select option", options: ["One-time", "Monthly", "Quarterly", "Annual", "Multi-year", "Ad hoc"] },
      { label: "Subscription model?", type: Select, placeholder: "Select option", options: ["Yes", "No"] },
      { label: "Gross margin range (%)", type: MinMax },
      { label: "LTV estimate ($)", type: MinMax },
      { label: "CAC target ($)", type: MinMax },
      { label: "Payback period target", type: Select, placeholder: "Select option", options: ["< 6 months", "6–12 months", "12–18 months", "18–24 months", "24+ months"] },
    ] },
    { title: "Funnel architecture", count: "6 fields", fields: [
      { label: "Main funnel path", type: Select, placeholder: "Select option", options: ["Self-serve", "Sales-led", "Product-led", "Marketing-led", "Hybrid"] },
      { label: "Key conversion events", type: MultiSelect, placeholder: "Select options", options: ["Sign up", "Demo booked", "Trial started", "Lead form", "Add to cart", "Checkout", "Purchase"], requiresBiz: true },
      { label: "Funnel ownership", type: Select, placeholder: "Select option", options: ["Marketing", "Sales", "Marketing → Sales", "Product", "Shared"] },
      { label: "Nurture path", type: Text, placeholder: "How prospects / customers are nurtured between funnel stages" },
      { label: "CRM stages", type: Area, placeholder: "List your CRM pipeline stages, one per line" },
      { label: "Ecommerce events", type: MultiSelect, placeholder: "Select options", options: ["Product view", "Add to cart", "Begin checkout", "Purchase", "Add to wishlist", "Search"], requiresBiz: true },
    ] },
    { title: "Website & platform signals", count: "6 fields", fields: [
      { label: "Website platform", type: Select, placeholder: "Select option", options: ["Webflow", "WordPress", "Shopify", "Wix", "Squarespace", "Custom", "Other"] },
      { label: "CRM", type: Select, placeholder: "Select option", options: ["HubSpot", "Salesforce", "Pipedrive", "Zoho", "Close", "None", "Other"] },
      { label: "Product catalog URL", type: Url, placeholder: "https://...", requiresBiz: true },
      { label: "Pricing page URL", type: Url, placeholder: "https://..." },
      { label: "Demo / contact URL", type: Url, placeholder: "https://...", requiresBiz: true },
      { label: "Checkout URL pattern", type: Text, placeholder: "e.g. /checkout", requiresBiz: true },
    ] },
  ] },
  { id: "reporting", title: "Reporting & Positioning", subtitle: "Set reporting preferences and the messaging that frames the brand.", completion: 0, caption: "Reporting preferences · Messaging & positioning", sections: [
    { title: "Reporting preferences", count: "5 fields", fields: [
      { label: "Cadence", type: Select, placeholder: "Select option", required: true, full: true, options: ["Daily", "Weekly", "Bi-weekly", "Monthly"] },
      { label: "Sections", type: MultiSelect, placeholder: "Select options", required: true, full: true, options: ["Status (green / yellow / red)", "Qualified demand summary", "CRO / site / dev changes", "Highlights", "KPIs", "Risks", "Actions", "Next steps"], chips: ["Status (green / yellow / red)", "Qualified demand summary", "CRO / site / dev changes"] },
      { label: "Tone", type: Select, placeholder: "Select option", required: true, full: true, options: ["Specific", "Concise", "Detailed", "Executive"] },
      { label: "Avoid", type: MultiSelect, placeholder: "Select options", required: true, full: true, options: ["Long metric dumps", "Vanity traffic wins without quality context", "Unsupported causal claims", "Jargon", "Speculation"], chips: ["Long metric dumps", "Vanity traffic wins without quality context", "Unsupported causal claims"] },
      { label: "Require human approval before posting", type: Toggle },
    ] },
    { title: "Messaging & positioning", count: "12 fields", fields: [
      { label: "Primary value proposition", type: Text },
      { label: "Emotional vs rational purchase driver", type: Text },
      { label: "Top 3 customer pains", type: Text },
      { label: "Top 3 desired outcomes", type: Text },
      { label: "Proof points", type: Text },
      { label: "Brand voice", type: Text },
      { label: "Claims allowed", type: Text },
      { label: "Claims prohibited", type: Text },
      { label: "Differentiators", type: Text },
      { label: "Competitor alternatives", type: Text },
      { label: "Common objections", type: Text },
      { label: "Urgency drivers", type: Text },
    ] },
  ] },
];
