import { ProfileFieldType, type ProfileStep } from "@/types/profile";

const { Text, Url, Select, Area, BigArea, Chips, MinMax, Toggle, BizModel } = ProfileFieldType;

export const PROFILE_STEPS: ProfileStep[] = [
  { id: "basic", title: "Basic Profile", subtitle: "Start with the core information required to create the client profile.", completion: 80, caption: "Client profile summary · Business overview", sections: [
    { title: "Client profile summary", count: "6 fields", fields: [
      { label: "Website", type: Url, placeholder: "Enter website", value: "https://northwindlabs.com", required: true, icon: "globe" },
      { label: "Business type", type: Select, placeholder: "Select business type", options: ["B2B", "D2C", "B2B2C", "Hybrid"] },
      { label: "Category", type: Text, placeholder: "Enter category", value: "B2B SaaS", icon: "building" },
      { label: "Primary growth motion", type: Area, placeholder: "Describe primary growth motion" },
      { label: "Primary AI digest goal", type: Select, placeholder: "Select primary AI digest goal", required: true, icon: "target", options: ["Track market and competitive trends", "Monitor campaign performance", "Identify growth opportunities", "Summarize weekly marketing insights"] },
      { label: "Main reporting risk", type: Select, placeholder: "Select main reporting risk", icon: "shield", options: ["Incomplete data", "Poor demand quality", "Bad-fit leads", "Competitive threats", "Unclear attribution"] },
    ] },
    { title: "Business overview", count: "7 fields", fields: [
      { label: "Business overview", type: BigArea, placeholder: "Describe business overview", required: true },
      { label: "Industry", type: Select, placeholder: "Enter industry", required: true, icon: "tag", options: ["Technology, Software", "Healthcare", "Financial Services", "Manufacturing", "Retail & E-commerce"] },
      { label: "Demand quality requirement", type: Select, placeholder: "Select demand quality requirement", options: ["High quality only", "Medium quality accepted", "Broad demand acceptable"] },
      { label: "Bad-fit lead risk", type: Select, placeholder: "Select bad-fit lead risk", options: ["Low", "Medium", "High"] },
      { label: "Regulated industry?", type: Toggle },
      { label: "Regulatory environment", type: Chips, placeholder: "Add regulatory environment", chips: ["HIPAA", "GDPR", "FDA", "ISO"] },
      { label: "Buying motions", type: Chips, placeholder: "Add buying motions", chips: ["Sales-led", "Product-led", "Partner-led", "Procurement-led"] },
    ] },
  ] },
  { id: "kpis", title: "KPIs & Objectives", subtitle: "Define the metrics that measure growth and the objectives behind them.", completion: 40, caption: "Primary & secondary KPIs · Goals & objectives", sections: [
    { title: "Primary and secondary KPIs", count: "6 fields", fields: [
      { label: "North star metric", type: Text, placeholder: "Enter north star metric", required: true },
      { label: "Primary KPIs — Qualified demo demand", type: Chips, placeholder: "Add qualified demo demand KPIs", required: true, chips: ["Demo requests", "SQLs"] },
      { label: "Primary KPIs — SEO-driven qualified demand", type: Chips, placeholder: "Add SEO-driven qualified demand KPIs", chips: [] },
      { label: "Primary KPIs — Paid media efficiency", type: Chips, placeholder: "Add paid media efficiency KPIs", chips: [] },
      { label: "Primary KPIs — CRO and landing page conversion quality", type: Chips, placeholder: "Add CRO and conversion quality KPIs", chips: [] },
      { label: "Secondary KPIs", type: Chips, placeholder: "Add secondary KPIs", chips: [] },
    ] },
    { title: "Goals and objectives", count: "1 field", fields: [
      { label: "Confirmed objectives", type: Area, placeholder: "Add confirmed objectives" },
    ] },
  ] },
  { id: "audience", title: "Audience & ICP", subtitle: "Describe who you sell to and how the audience is segmented.", completion: 20, caption: "Target audience / ICP · Audience & segmentation", sections: [
    { title: "Target audience / ICP", count: "10 fields", fields: [
      { label: "Company type", type: Chips, placeholder: "Add company types", required: true, chips: ["Enterprise", "Mid-market"] },
      { label: "Commercialization stage", type: Chips, placeholder: "Add commercialization stages", chips: [] },
      { label: "Geography", type: Chips, placeholder: "Add geography", chips: [] },
      { label: "Device risk profile", type: Chips, placeholder: "Add device risk profiles", chips: [] },
      { label: "Functional buyers", type: Chips, placeholder: "Add functional buyers", chips: [] },
      { label: "Target titles", type: Chips, placeholder: "Add target titles", chips: [] },
      { label: "Pre market", type: Area, placeholder: "Describe pre market segment" },
      { label: "Post market", type: Area, placeholder: "Describe post market segment" },
      { label: "SaMD", type: Area, placeholder: "Describe SaMD segment" },
      { label: "Bad-fit / low-fit audiences", type: Chips, placeholder: "Add bad-fit / low-fit audiences", chips: [] },
    ] },
    { title: "Audience & segmentation", count: "20 fields", conditional: true, helper: "For B2B, collect firmographics. For D2C, collect consumer attributes.", fields: [
      { label: "Target industries", type: Chips, placeholder: "Add target industries", chips: [], group: "b2b" },
      { label: "Company size", type: Select, placeholder: "Select company size", options: ["1–50", "51–200", "201–1,000", "1,000+"], group: "b2b" },
      { label: "Revenue range", type: Text, placeholder: "e.g. $10M–$50M", group: "b2b" },
      { label: "Target departments", type: Chips, placeholder: "Add target departments", chips: [], group: "b2b" },
      { label: "Buyer titles", type: Chips, placeholder: "Add buyer titles", chips: [], group: "b2b" },
      { label: "Procurement objections", type: Area, placeholder: "Describe procurement objections", group: "b2b" },
      { label: "Compliance requirements", type: Chips, placeholder: "Add compliance requirements", chips: [], group: "b2b" },
      { label: "Existing competitors", type: Chips, placeholder: "Add existing competitors", chips: [], group: "b2b" },
      { label: "Geography served", type: Chips, placeholder: "Add geography served", chips: [], group: "both" },
      { label: "Pain points by role", type: Area, placeholder: "Describe pain points by role", group: "both" },
      { label: "Target demographics", type: Area, placeholder: "Describe target demographics", group: "d2c" },
      { label: "Psychographics", type: Area, placeholder: "Describe psychographics", group: "d2c" },
      { label: "Lifestyle triggers", type: Chips, placeholder: "Add lifestyle triggers", chips: [], group: "d2c" },
      { label: "Purchase occasions", type: Chips, placeholder: "Add purchase occasions", chips: [], group: "d2c" },
      { label: "Gift vs self purchase", type: Select, placeholder: "Select purchase type", options: ["Gift", "Self", "Both"], group: "d2c" },
      { label: "Price sensitivity", type: Select, placeholder: "Select price sensitivity", options: ["Low", "Medium", "High"], group: "d2c" },
      { label: "Product preference drivers", type: Chips, placeholder: "Add product preference drivers", chips: [], group: "d2c" },
      { label: "Pre-purchase objections", type: Area, placeholder: "Describe pre-purchase objections", group: "d2c" },
      { label: "Reviews / testimonials", type: Text, placeholder: "Link or describe reviews", group: "d2c" },
      { label: "UGC available?", type: Select, placeholder: "Select", options: ["Yes", "No"], group: "d2c" },
    ] },
  ] },
  { id: "products", title: "Products & Offer", subtitle: "Detail what you sell and how complex the offer is to buy.", completion: 0, caption: "Products & services · Offer & product complexity", sections: [
    { title: "Products and services", count: "5 fields", fields: [
      { label: "Quality Management / eQMS", type: Chips, placeholder: "Add quality management / eQMS offerings", chips: [] },
      { label: "Product Development", type: Chips, placeholder: "Add product development offerings", chips: [] },
      { label: "Clinical Evidence", type: Chips, placeholder: "Add clinical evidence offerings", chips: [] },
      { label: "Education & Services", type: Chips, placeholder: "Add education & services offerings", chips: [] },
      { label: "AI, Data & Intelligence", type: Chips, placeholder: "Add AI, data & intelligence offerings", chips: [] },
    ] },
    { title: "Offer & product complexity", count: "8 fields", fields: [
      { label: "Product / service complexity", type: Select, placeholder: "Select complexity", options: ["Low", "Medium", "High"] },
      { label: "Customization required?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Implementation required?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Onboarding process", type: Area, placeholder: "Describe onboarding process" },
      { label: "Number of SKUs", type: Text, placeholder: "e.g. 24" },
      { label: "Product variants?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Shipping / fulfillment?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Returns / refunds policy URL", type: Url, placeholder: "https://…" },
    ] },
  ] },
  { id: "competitors", title: "Competitors & Campaigns", subtitle: "Capture the competitive landscape and current marketing activity.", completion: 0, caption: "Competitors · Active campaigns · Channel mix", sections: [
    { title: "Competitors", count: "6 fields", fields: [
      { label: "Priority competitors", type: Chips, placeholder: "Add priority competitors", chips: [] },
      { label: "Public comparison competitors", type: Chips, placeholder: "Add public comparison competitors", chips: [] },
      { label: "QMS / eQMS", type: Chips, placeholder: "Add QMS / eQMS competitors", chips: [] },
      { label: "Product development / design controls", type: Chips, placeholder: "Add competitors", chips: [] },
      { label: "Clinical / EDC", type: Chips, placeholder: "Add clinical / EDC competitors", chips: [] },
      { label: "Alternatives / status quo", type: Chips, placeholder: "Add alternatives / status quo", chips: [] },
    ] },
    { title: "Active campaigns and projects", count: "5 fields", fields: [
      { label: "SEO and organic growth", type: Area, placeholder: "Describe SEO and organic growth work" },
      { label: "Paid search", type: Area, placeholder: "Describe paid search campaigns" },
      { label: "LinkedIn", type: Area, placeholder: "Describe LinkedIn campaigns" },
      { label: "Reddit", type: Area, placeholder: "Describe Reddit campaigns" },
      { label: "CRO projects", type: Area, placeholder: "Describe CRO projects" },
    ] },
    { title: "Marketing channel mix", count: "9 fields", fields: [
      { label: "Current acquisition channels", type: Chips, placeholder: "Add acquisition channels", chips: [] },
      { label: "Primary paid channel", type: Select, placeholder: "Select primary paid channel", options: ["Google Ads", "LinkedIn Ads", "Meta Ads", "Reddit Ads"] },
      { label: "Organic search focus", type: Text, placeholder: "Describe organic search focus" },
      { label: "Social proof assets", type: Chips, placeholder: "Add social proof assets", chips: [] },
      { label: "Influencer / creator strategy?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Sales outbound motion?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Affiliate program?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Partner / channel sales?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Highest-quality customer channel", type: Text, placeholder: "e.g. Referrals" },
    ] },
  ] },
  { id: "buyer", title: "Buyer, Sales & Funnel", subtitle: "Map how customers buy, the sales motion, revenue model, and funnel.", completion: 0, caption: "Buyer structure · Sales · Revenue · Funnel · Signals", sections: [
    { title: "Customer / buyer structure", count: "8 fields", fields: [
      { label: "Business model (B2B / D2C)", type: BizModel, icon: "briefcase" },
      { label: "Primary buyer type", type: Text, placeholder: "e.g. Economic buyer" },
      { label: "People involved in purchase", type: Text, placeholder: "e.g. 3–5 stakeholders" },
      { label: "Buyer role", type: Text, placeholder: "e.g. VP Operations" },
      { label: "End user differs from buyer?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Buyer vs user notes", type: Area, placeholder: "Describe buyer vs user differences" },
      { label: "Account type — household vs company", type: Select, placeholder: "Select account type", options: ["Household", "Company"] },
      { label: "Customer examples", type: Area, placeholder: "List example customers" },
    ] },
    { title: "Sales motion", count: "7 fields", helper: "One of the strongest B2B vs D2C differentiators.", fields: [
      { label: "Primary conversion goal", type: Text, placeholder: "e.g. Book a demo" },
      { label: "Sales cycle length", type: Select, placeholder: "Select sales cycle length", options: ["< 1 week", "1–4 weeks", "1–3 months", "3–6 months", "6+ months"] },
      { label: "Human sales involvement", type: Select, placeholder: "Select", options: ["None", "Light", "Heavy"] },
      { label: "Pricing visibility", type: Select, placeholder: "Select", options: ["Public", "Gated"] },
      { label: "Contract required?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Purchase approval required?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Can a new customer buy online without talking to sales?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
    ] },
    { title: "Revenue model", count: "8 fields", helper: "D2C is usually AOV/LTV/CAC driven; B2B is usually ACV/pipeline/payback/sales-cycle driven.", fields: [
      { label: "Avg order / contract value", type: MinMax, unit: "$" },
      { label: "Revenue unit", type: Text, placeholder: "e.g. Per seat / per order" },
      { label: "Repeat purchase frequency", type: Text, placeholder: "e.g. Annual renewal" },
      { label: "Subscription model?", type: Select, placeholder: "Select", options: ["Yes", "No"] },
      { label: "Gross margin range", type: MinMax, unit: "%" },
      { label: "LTV estimate", type: MinMax, unit: "$" },
      { label: "CAC target", type: MinMax, unit: "$" },
      { label: "Payback period target", type: Text, placeholder: "e.g. 12 months" },
    ] },
    { title: "Funnel architecture", count: "6 fields", fields: [
      { label: "Main funnel path", type: Area, placeholder: "Describe the main funnel path" },
      { label: "Key conversion events", type: Chips, placeholder: "Add key conversion events", chips: [] },
      { label: "Funnel ownership", type: Text, placeholder: "e.g. Marketing → Sales" },
      { label: "Nurture path", type: Area, placeholder: "Describe the nurture path" },
      { label: "CRM stages", type: Area, placeholder: "One stage per line", fieldHelper: "List your CRM pipeline stages, one per line." },
      { label: "Ecommerce events", type: Chips, placeholder: "Add ecommerce events", chips: [] },
    ] },
    { title: "Website & platform signals", count: "6 fields", fields: [
      { label: "Website platform", type: Text, placeholder: "e.g. Webflow" },
      { label: "CRM", type: Text, placeholder: "e.g. HubSpot" },
      { label: "Product catalog URL", type: Url, placeholder: "https://…" },
      { label: "Pricing page URL", type: Url, placeholder: "https://…" },
      { label: "Demo / contact URL", type: Url, placeholder: "https://…" },
      { label: "Checkout URL pattern", type: Text, placeholder: "e.g. /checkout" },
    ] },
  ] },
  { id: "reporting", title: "Reporting & Positioning", subtitle: "Set reporting preferences and the messaging that frames the brand.", completion: 0, caption: "Reporting preferences · Messaging & positioning", sections: [
    { title: "Reporting preferences", count: "5 fields", fields: [
      { label: "Cadence", type: Select, placeholder: "Select cadence", options: ["Daily", "Weekly", "Bi-weekly", "Monthly"] },
      { label: "Sections", type: Chips, placeholder: "Add sections", chips: ["Highlights", "KPIs", "Risks", "Actions"] },
      { label: "Tone", type: Select, placeholder: "Select tone", options: ["Concise", "Detailed", "Executive"] },
      { label: "Avoid", type: Chips, placeholder: "Add things to avoid", chips: [] },
      { label: "Require human approval before posting", type: Toggle },
    ] },
    { title: "Messaging & positioning", count: "12 fields", fields: [
      { label: "Primary value proposition", type: Area, placeholder: "Describe the primary value proposition" },
      { label: "Emotional vs rational purchase driver", type: Select, placeholder: "Select", options: ["Emotional", "Rational", "Balanced"] },
      { label: "Top 3 customer pains", type: Chips, placeholder: "Add customer pains", chips: [] },
      { label: "Top 3 desired outcomes", type: Chips, placeholder: "Add desired outcomes", chips: [] },
      { label: "Proof points", type: Chips, placeholder: "Add proof points", chips: [] },
      { label: "Claims allowed", type: Area, placeholder: "Describe claims allowed" },
      { label: "Brand voice", type: Select, placeholder: "Select brand voice", options: ["Professional", "Friendly", "Bold", "Technical"] },
      { label: "Claims prohibited", type: Area, placeholder: "Describe claims prohibited" },
      { label: "Differentiators", type: Chips, placeholder: "Add differentiators", chips: [] },
      { label: "Competitor alternatives", type: Chips, placeholder: "Add competitor alternatives", chips: [] },
      { label: "Common objections", type: Chips, placeholder: "Add common objections", chips: [] },
      { label: "Urgency drivers", type: Chips, placeholder: "Add urgency drivers", chips: [] },
    ] },
  ] },
];
