import type { QueueItem } from "@/types/queue";

export const QUEUE: QueueItem[] = [
  { id: "Q-1044", task: "Daily Growth Pulse — Northwind Labs", client: "Northwind Labs", type: "AI Digest", status: "Pending", priority: "High", created: "Jun 24, 2026", updated: "2h ago", integration: null, isDigest: true,
    description: "AI-generated daily Slack digest assembled from 13 sources. Ready for strategist review before sending to #northwind-growth.",
    timeline: [{ text: "Digest assembled from 13 sources", time: "Jun 24, 2026 · 7:01 AM", kind: "done" }, { text: "Queued for admin verification", time: "Jun 24, 2026 · 7:02 AM", kind: "done" }, { text: "Data quality check completed", time: "Jun 24, 2026 · 7:03 AM", kind: "done" }, { text: "Ready for strategist review", time: "Jun 24, 2026 · 7:03 AM", kind: "active" }] },
  { id: "Q-1042", task: "Profile Review — Northwind Labs", client: "Northwind Labs", type: "Profile Review", status: "Pending", priority: "High", created: "Jun 21, 2026", updated: "2h ago", integration: null,
    description: "New profile fields were submitted via magic link and need admin review before the AI analysis can run.",
    timeline: [{ text: "Magic link submitted by client", time: "Jun 21, 2026 · 9:41 AM", kind: "done" }, { text: "Queued for admin review", time: "Jun 21, 2026 · 9:42 AM", kind: "active" }] },
  { id: "Q-1041", task: "Integration Sync — HubSpot", client: "Brightwave Media", type: "Integration Sync", status: "In Progress", priority: "Medium", created: "Jun 21, 2026", updated: "20m ago", integration: "HubSpot",
    description: "Pulling contacts, deals, and marketing activity from HubSpot into the client workspace.",
    timeline: [{ text: "Sync started", time: "Jun 21, 2026 · 11:10 AM", kind: "done" }, { text: "Importing 4,210 contacts", time: "In progress", kind: "active" }] },
  { id: "Q-1040", task: "AI Analysis — Funnel signals", client: "Halcyon Health", type: "AI Analysis", status: "Completed", priority: "Low", created: "Jun 20, 2026", updated: "Yesterday", integration: null,
    description: "AI analysis of funnel architecture and website signals to surface conversion opportunities.",
    timeline: [{ text: "Analysis started", time: "Jun 20, 2026 · 2:00 PM", kind: "done" }, { text: "Report generated", time: "Jun 20, 2026 · 2:06 PM", kind: "done" }] },
  { id: "Q-1039", task: "Magic Link Request", client: "Vertex Logistics", type: "Magic Link Request", status: "Pending", priority: "Medium", created: "Jun 20, 2026", updated: "1 day ago", integration: null,
    description: "Client requested a fresh magic link to update their profile and onboarding details.",
    timeline: [{ text: "Request received", time: "Jun 20, 2026 · 4:30 PM", kind: "active" }] },
  { id: "Q-1038", task: "Data Import — CSV contacts", client: "Lumen Retail", type: "Data Import", status: "In Progress", priority: "High", created: "Jun 20, 2026", updated: "3h ago", integration: null,
    description: "Importing a 12,400-row CSV of contacts and segmenting by lifecycle stage.",
    timeline: [{ text: "Upload received", time: "Jun 20, 2026 · 8:15 AM", kind: "done" }, { text: "Validating rows", time: "In progress", kind: "active" }] },
  { id: "Q-1037", task: "Integration Sync — Salesforce", client: "Cedar & Co.", type: "Failed Sync", status: "Failed", priority: "High", created: "Jun 19, 2026", updated: "2 days ago", integration: "Salesforce",
    description: "Scheduled Salesforce sync to refresh accounts, opportunities, and pipeline data.",
    error: "Authentication token expired. Salesforce returned 401 Unauthorized during the scheduled sync. Reconnect the integration and retry.",
    timeline: [{ text: "Sync scheduled", time: "Jun 19, 2026 · 6:00 AM", kind: "done" }, { text: "Authentication failed (401)", time: "Jun 19, 2026 · 6:01 AM", kind: "failed" }] },
  { id: "Q-1036", task: "AI Analysis — Competitor scan", client: "Brightwave Media", type: "AI Analysis", status: "Completed", priority: "Low", created: "Jun 18, 2026", updated: "4 days ago", integration: null,
    description: "Competitive landscape scan across messaging, pricing, and channel mix.",
    timeline: [{ text: "Analysis started", time: "Jun 18, 2026 · 10:00 AM", kind: "done" }, { text: "Report generated", time: "Jun 18, 2026 · 10:09 AM", kind: "done" }] },
  { id: "Q-1035", task: "Profile Review — Lumen Retail", client: "Lumen Retail", type: "Profile Review", status: "Pending", priority: "Low", created: "Jun 18, 2026", updated: "4 days ago", integration: null,
    description: "Updated positioning and channel mix submitted for review.",
    timeline: [{ text: "Profile updated by client", time: "Jun 18, 2026 · 1:20 PM", kind: "active" }] },
];
